[settings]
jobs=1

[tools]
github-cli = "latest"
go = "1.22.0"
golangci-lint = "latest"
hurl = "latest"
jq = "latest"
shellcheck = "latest"
shfmt = "latest"

[env]
GO111MODULE = "on"
CGO_ENABLED = "0"

[tasks.deps]
description = "Download and tidy dependencies"
run = "go mod tidy"
sources = ["go.*"]
outputs = { auto = true }

#TODO proc je to samostatny program
[tasks.config-check]
description = "Validate configuration file"
run = "go run ./cmd/config-validator/main.go ./config/example.yaml && go run ./cmd/config-validator/main.go ./config/test.yaml"
sources = ["go.*", "cmd/**/*.go", "internal/**/*.go"]
outputs = { auto = true }

[tasks.build]
description = "Build the weblogproxy binary"
run = "go build -o weblogproxy ./cmd/weblogproxy"
depends = ["deps"]
sources = ["go.*", "cmd/**/*", "internal/**/*"]
outputs = "weblogproxy"

[tasks.run]
description = "Run the weblogproxy service with example config"
run = "go run ./cmd/weblogproxy -config config/example.yaml"
depends = ["config-check", "deps"]

[tasks.run-test]
description = "Run the weblogproxy service with test config"
run = "go run ./cmd/weblogproxy -config config/test.yaml"
depends = ["config-check", "deps"]

[tasks.test-unit]
description = "Spustí pouze unit testy"
run = "go test -v ./..."

[tasks.test-e2e]
description = "Spustí pouze E2E testy"
run = "./test/run.sh"
depends = ["build"]

[tasks.test]
description = "Spustí všechny testy pro app"
wait_for = ["build", "config-check"]
depends = ["test-unit", "test-e2e"]

[tasks.test-all]
description = "Spustí všechny testy pro app i docker"
depends = ["test", "docker-test"]

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.docker-build]
description = "Build Docker image"
run = "./scripts/docker-build.sh"
sources = ["Dockerfile", "cmd/**/*", "internal/**/*"]
outputs = { auto = true }
depends = ["test"]

[tasks.docker-run]
description = "Run Docker container"
run = "docker run -p 8080:8080 -v $(pwd)/config/example.yaml:/app/config/config.yaml weblogproxy:latest"
depends = ["docker-build"]

[tasks.docker-test]
description = "Test Docker image build and functionality"
run = "./scripts/docker-test.sh"
sources = ["Dockerfile", "cmd/**/*", "internal/**/*"]
outputs = { auto = true }
depends = ["docker-build"]

[tasks.docker-ssh-copy]
description = "Deploy Docker image to remote server via SSH (usage: mise run docker-ssh-copy -- [server] [additional_ssh_options])"
run = "./scripts/docker-ssh-copy.sh ${@}"
depends = ["docker-test"]

[tasks.version-bump]
description = "Bump version (usage: mise run version-bump -- [major|minor|patch])"
run = "./scripts/bump-version.sh -y ${@}"

[tasks.publish]
description = "Publish version (usage: mise run publish -- [version])"
run = "./scripts/publish.sh ${@}"
depends = ["test", "docker-test"]

[tasks.clean]
description = "Clean build artifacts"
run = "rm -rf bin/ dist/"

[tasks.dev]
description = "Run development server with hot reload"
run = "air -c .air.toml"

[tasks.docs]
description = "Generate API documentation"
run = "swag init -g cmd/weblogproxy/main.go -o docs/swagger"
